name: "Static Analysis"

on:
  pull_request:
    paths:
      - .github/workflows/static-analysis.yml
      - composer.*
      - phpstan.neon.dist
      - src/**
      - static-analysis/**
      - tests/**
  push:
    paths:
      - .github/workflows/static-analysis.yml
      - composer.*
      - phpstan.neon.dist
      - src/**
      - static-analysis/**
      - tests/**

jobs:
  static-analysis-phpstan:
    name: "Static Analysis"
    uses: "doctrine/.github/.github/workflows/phpstan.yml@15.0.0"
